### ISSUE TITLE
active route?

### ISSUE THREAD

**Issue by chovy** [jorgegorka/svelte-router#13]
I need to create this base on the active route:

`<li class="active"><a href="/dashboard">Dashboard</a></li>`

Is there a simple way to do this?

**Comment by jorgegorka** [comment]
Hi @chovy 

There is a `routeIsActive` helper that you can use

```:javascript
import { routeIsActive } from 'svelte-router-spa'

<li class:active={routeIsActive('dashboard')}>
  <a href="/dashboard">Dashboard</a>
</li>
```

Hope this helps,

**Comment by chovy** [comment]
perfect, thanks.

**Comment by chovy** [comment]
Doesn't seem to work for me.

`<li class:active={routeIsActive('pricing')}><Navigate to="/pricing">Pricing</Navigate></li>`

**Comment by jorgegorka** [comment]
Check out that the component is refreshed after a route change.   Svelte does a very good job only refreshing components that have changed and ignoring the rest.  I think in your case the menu component is not being refreshed and therefore the code is not evaluated.

It's very easy to check. If you click a link to `/pricing` and it's not active but when you reload the page `/pricing` it's active then it's a problem with that component not being refreshed.

**Comment by chovy** [comment]
now the active class is always there. even when changing routes.

**Comment by chovy** [comment]
https://puump.com/pricing

**Comment by jorgegorka** [comment]
Please check this code. Here is working as expected.

https://github.com/jorgegorka/demanda/blob/master/frontend/src/views/protected/admin/layout/main_menu/item.svelte

**Comment by chovy** [comment]
How come my code doesn't work? Am I missng something?

**Comment by jorgegorka** [comment]
You need to export currentRoute `export let currentRoute`

**Comment by chovy** [comment]
still doesn't work.

```
<script>
    import { Router } from 'svelte-router-spa'
    import Navbar from './components/Navbar.svelte';
    import Topnav from './components/Topnav.svelte';
    import routes from './routes';
    import style from '../public/styles/global.css';

    export let currentRoute
</script>

<main>
    <Navbar {currentRoute} />
    <div id="body">
        <Topnav />
        <Router {routes} />
    </div>
</main>
```

**Comment by jorgegorka** [comment]
There is a problem with this approach. It is the `Router` component the one that send the `currentRoute` info to the children. In your example `Navbar` can not use `currentRoute` because it's defined inside the `Router`:

The `Router` needs to be higher in the component hierarchy.  Check this two files as an example:

Router is the top level component:

https://github.com/jorgegorka/demanda/blob/e687d761ebe284c7dd7e8f033787eccc250f8523/frontend/src/App.svelte#L6

Layout receives `currentRoute` and send it `MainMenu` and `Route` (not Router) 

https://github.com/jorgegorka/demanda/blob/e687d761ebe284c7dd7e8f033787eccc250f8523/frontend/src/views/protected/admin/layout/index.svelte#L53-L60

**Comment by chovy** [comment]
is there a simpler example of how to pass {currentRoute}?

**Comment by chovy** [comment]
So i got it sort of working. Navigating between routes doesn't set the active class, but if I refresh the page it works.

https://puump.com/signup go here and then click on Pricing. You won't get the active class on Pricing nav but if you refresh it appears.

**Comment by classikd** [comment]
Same for me, quiet hard to manage active links.
There is no reactivity when pages change

**Comment by chovy** [comment]
I think this project is still working out the kinks.

**Comment by jorgegorka** [comment]
Hi @classikd and @chovy 

There is no reactivity because in your component nothing has changed.  In an SPA the fact that a route has been changed does not make all components to be recreated.  That would be a waste of resources.

So if you want an specific component to be updated when a route changes you need to add some reactive information to that component.

Check this example: 

https://github.com/jorgegorka/demanda/blob/f13be6c2cae23ff6aeb27e37fdb336bb83211544/frontend/src/views/protected/admin/layout/main_menu/item.svelte#L9-L13

 In an SPA the fact that a route has been changed does not make all components to be recreated.  That would be a waste of resources.

See how using Svelte _$:_ and _currentRoute_ (because the value of currentRoute changes when the active route changes) we create the reactivity we need for the component to be updated.

**Comment by chovy** [comment]
classes aren't applied correctly for svelte namesapcing of css

```
            <li class:active={routeIsActive('login')}>
                <Navigate to="/login">
                    <span class="icon">a</span> Login
                </Navigate>
            </li>
```

This code is not rendered properly given the following css:

```
    li a {
        display: flex;
        justify-content: flex-start;
        align-items: center;
        padding: .4rem;
        color: var(--main-nav-link-color);
        font-weight: 700;

    }

    li .icon {
        width: 5rem;
        height: 5rem;
        background-color: var(--main-nav-link-icon-bg-color);
        display: flex;
        justify-content: center;
        align-items: center;
        margin-right: 1rem;
        border-radius: .5rem;
        color: var(--main-nav-link-icon-color);
    }
```

**Comment by solnsumei** [comment]
You can check the `currentRoute.childRoute.name` if it is a nested route and use it to set the active route.

**Comment by chovy** [comment]
this still broken for me.
