### ISSUE TITLE
namedParams are undefined.

### ISSUE THREAD

**Issue by jhon-andrew** [jorgegorka/svelte-router#36]
I defined a route like this:

```js
{
  name: "/page/:id",
  component: Page
}
```

...and in the `Page` component, I am console logging `currentRoute.namedParams`. I do get the property name `id` but it is undefined. It seems like it doesn't define what is supplied in the route. Is there something I am missing or this is actually an issue?

**Comment by jorgegorka** [comment]
Hello @jhon-andrew 

I'm reopening this issue as it is an actual  bug.

Routes should work no matter if a `/` is added at the beginning.  I'm working on the fix.

Thanks for noticing this.

**Comment by rvanderfeer** [comment]
I experienced what - I think - is a related issue when trying to create a nested route that only has a named param component; eg. 

This did not work for me;
```javascript
{
    name: "pages",
    component: PageList,
    nestedRoutes: [
        name: ":id",
        component: Page
    ]
}
```

This did;
```javascript
{
    name: "pages",
    component: PageList
}, {
    name: "pages/:id",
    component: Page
}
```

I had a preference for the use of nestedRoutes as it would enable a less verbose layout inheritance but the 2nd format is otherwise fine.

**Comment by jorgegorka** [comment]
Hello @rvanderfeer 

Named params are optional so there is no way they can be on a route on their own.  They always need to be as path name + named param as you did in your second example.

Best,
